files:
  -
    source: '/**/gitXpath.*'
    translatable_elements:
      - '/resources/string'
    ignore:
      - '1fr_strings.xml'
    translation: '/**/%two_letters_code%_%original_file_name%'
    first_line_contains_header: true
    scheme: "identifier,source_phrase,context,uk,fr"
    multilingual_spreadsheet: true

